# This is a basic workflow to help you get started with Actions

name: Build Release V2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]

jobs:

  build_1_19:
    uses: jsmacros/jsmacros/.github/workflows/releasebuild.yml@main-1.19
    with:
      branch: tsconfig2
      java_version: 17

  deploy_1_19:
    uses: jsmacros/jsmacros/.github/workflows/releasedeploy.yml@main-1.19
    with:
      branch: tsconfig2
      game_vers: 1.19
      java_vers: 17
      GITHUB_REF: ${{ github.ref }}
    secrets:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    needs:
      - build_1_19

  upload_pydoc:
    runs-on: ubuntu-latest
    needs:
      - build_1_19
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: main-1.19
          path: dist

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python Deps
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Upload PyDoc
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          ls .
          ls dist
          cd dist/python
          python setup.py sdist bdist_wheel
          twine upload dist/*

  publish_npm:
    runs-on: ubuntu-latest
    needs:
      - build_1_19
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: main-1.19
          path: dist
      - uses: actions/setup-node@v3
        name: Setup node
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com/

      - name: Publish to node
        run: |
          ls .
          ls dist
          cd dist/typescript
          npm publish

